name: tabunganku
description: A new Flutter project for saving money online.
publish_to: 'none'
version: 1.5.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  google_fonts: 8.0.2
  fl_chart: ^0.66.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  flutter_local_notifications: ^17.2.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  permission_handler: ^11.3.1
  
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.14
  crypto: ^3.0.3
  
  # State Management & Routing
  go_router: ^11.1.2
  
  # Data Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  timezone: ^0.9.4
  flutter_timezone: ^5.0.2
  
  
  # Data Models
  image_picker: ^1.0.7
  share_plus: ^12.0.2
  path: ^1.9.1
  google_mlkit_text_recognition: ^0.13.0
  url_launcher: ^6.3.2
  flutter_native_contact_picker: ^0.0.11
  connectivity_plus: ^7.1.1
  http: ^1.6.0
  uuid: ^4.3.3
  image_cropper: 8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
